title: "Upendra Goswami Blogs"
description: "Blog"
url: "https://upendra-goswami.github.io" # GitHub Pages URL

# Remote theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

author:
  name: "Upendra Goswami"
  email: "nbpgoswamiupendra@gmail.com"
  bio: "Adobe Commerce Expert | Team Lead | Magento Developer"
  avatar: "/assets/images/profile.jpg"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "nbpgoswamiupendra@gmail.com"
  - label: "Linkedin"
    icon: "fab fa-fw fa-linkedin-in"
    url: "https://linkedin.com/in/upendra-goswami"

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

social:
  - icon: fab fa-github
    link: https://github.com/upendra-goswami
  - icon: fab fa-linkedin
    link: https://linkedin.com/in/upendra-goswami

collections:
  pages:
    output: true
    permalink: /:path/

logo: "/assets/images/logo.png"