title: "Upendra Goswami Blogs"
description: "Blog"
url: "https://upendra-goswami.github.io" # GitHub Pages URL

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

author:
  name: "Upendra Goswami"
  bio: "Adobe Commerce Expert | Team Lead | Magento Developer"
  avatar: "/assets/images/profile.jpg"

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

minimal_mistakes_skin: "default"
